from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]
    strategy_mode: Annotated[str, "Graph execution mode: single_stock or overnight"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]

    # Global market context (US indices, macro news) for cross-market analysis
    global_market_context: Annotated[str, "Global market context (US indices, macro sentiment) for A-share analysis"]

    # Overnight strategy context
    overnight_context: Annotated[str, "Overnight market and strategy context summary"]
    candidate_universe_summary: Annotated[str, "Summary of the overnight candidate universe for the trade date"]
    candidate_snapshot: Annotated[str, "Structured snapshot of overnight candidates, scores, and risk flags"]
    baseline_reference_picks: Annotated[str, "Reference picks from the baseline overnight strategy"]
    strict_risk_reference_picks: Annotated[str, "Reference picks from the strict_risk overnight strategy"]
    screened_candidates: Annotated[str, "Candidates remaining after overnight screening and filtering"]
    selected_candidates: Annotated[str, "Final candidate selections proposed by the agent graph"]
    rejected_candidates: Annotated[str, "Rejected overnight candidates and their reasons"]
    selection_constraints: Annotated[str, "Constraints used for nightly selection such as top_n, filter variant, and cash allowance"]
    selection_rationale: Annotated[str, "Why the final overnight candidates were selected"]
    override_reasons: Annotated[str, "Reasons the agent graph overrode baseline or strict_risk picks"]
    rejected_reason_map: Annotated[str, "Per-symbol rejection reasons for audit and diagnostics"]
    portfolio_construction_plan: Annotated[str, "Structured overnight portfolio construction plan before final review"]
    final_portfolio: Annotated[str, "Final overnight portfolio with picks, weights, and execution notes"]
